module Config {
    const USE_DEMO_DATA = false;

    const API_URL =
        "https://h0me-p0wer.lucianhanga.stream/api/watch/status";

    // Sent as "Authorization: Bearer <token>" when non-empty (see
    // HomePowerService.refresh) — matches the backend's optional API
    // token auth (h0me-p0wer repo, server/auth.js/generate-token.js).
    // Lives in Secrets.mc (gitignored — copy Secrets.mc.example to create
    // it) rather than here, so a real token never lands in git. Set it to
    // the SAME value generated by `npm run token:generate`. Expires after
    // 4 weeks — renewal is manual: regenerate, update Secrets.mc, rebuild,
    // reinstall.
    const API_TOKEN = Secrets.API_TOKEN;

    const REFRESH_MS = 15000;
}
