module Config {
    const USE_DEMO_DATA = false;

    const API_URL =
        "https://h0me-p0wer.lucianhanga.stream/api/watch/status";

    // Sent as "Authorization: Bearer <token>" when non-empty (see
    // HomePowerService.refresh) — matches the backend's optional API
    // token auth (h0me-p0wer repo, server/auth.js/generate-token.js).
    // Leave "" while the backend has no token configured yet (auth fails
    // open there); set it to the SAME value generated by
    // `npm run token:generate` once it does. Expires after 4 weeks —
    // renewal is manual: regenerate, update this, rebuild, reinstall.
    const API_TOKEN = "";

    const REFRESH_MS = 15000;
}
